# coding: utf-8

# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

# Division(部署)テーブルに初期値を投入(全件削除して再投入)
Division.delete_all
Division.create(id: 1, code: 'HdO-01', name: '本社')
Division.create(id: 2, code: 'OSK-01', name: '大阪第１')
Division.create(id: 3, code: 'OSK-02', name: '大阪第２')
Division.create(id: 4, code: 'NGY-01', name: '名古屋営業所')
Division.create(id: 5, code: 'TKY-01', name: '東京支社')
if Rails.env.development?
  Division.connection.execute("update sqlite_sequence set seq=5 where name='divisions'")
else
  Division.connection.execute("SELECT SETVAL('divisions_id_seq', 5, TRUE)")
end

# Type(種類)テーブルに初期値を投入(全件削除して再投入)
Type.delete_all
Type.create(id: 1, name: '通常用')
Type.create(id: 2, name: '非常用')
Type.create(id: 3, name: '携帯用')
if Rails.env.development?
  Type.connection.execute("update sqlite_sequence set seq=3 where name='types'")
else
  Type.connection.execute("SELECT SETVAL('types_id_seq', 3, TRUE)")
end

# Place(場所)テーブルに初期値を投入(全件削除して再投入)
Place.delete_all

Place.create(id: 1, name: 'ゴム工業エイチ関西株式会社', address: '七尾市中島町大平91丁目523-4580' )
Place.create(id: 2, name: '株式会社インキ丸紅マキタ', address: '鳥取市気高町下坂本70丁目2807-8603' )
Place.create(id: 3, name: '高崎健康福祉大学', address: '大阪府堺市南区新檜尾台' )
Place.create(id: 4, name: '大機グループヤマト有限会社', address: '登米市米山町西野58丁目5638-7130' )
Place.create(id: 5, name: '大丸システムズ内外株式会社', address: '本巣市木知原99丁目8635-2984' )
Place.create(id: 6, name: '北九州大学', address: '徳島県徳島市国府町東黒田' )
Place.create(id: 7, name: '大機テトラエー株式会社', address: '小豆郡小豆島町田浦81丁目1076-193' )
Place.create(id: 8, name: 'セブンティサン有限会社', address: '北設楽郡設楽町三都橋60丁目3206-7865' )
Place.create(id: 9, name: '株式会社協和高島宇部', address: '中頭郡北中城村大城57丁目7067-9176' )
Place.create(id: 10, name: '株式会社ハルテックバルブホームズ', address: '西尾市吉良町大島92丁目3396-1213' )
Place.create(id: 11, name: 'ユアサ九州グループ組合', address: '富山市下栗山73丁目9833-6589' )
Place.create(id: 12, name: '金沢大学', address: '京都府京都市山科区西野小柳町' )
Place.create(id: 13, name: '山口福祉文化大学', address: '青森県三沢市三沢' )
Place.create(id: 14, name: '株式会社マキタ京王両備', address: '大阪市此花区島屋54丁目7042-3946' )
Place.create(id: 15, name: 'テクノロジー東和丸紅株式会社', address: '岡山市北区島田本町83丁目8506-5154' )
Place.create(id: 16, name: '大阪国際大学', address: '愛知県稲沢市一色道上町' )
Place.create(id: 17, name: '岐阜薬科大学', address: '愛知県豊川市御津町赤根松葉' )
Place.create(id: 18, name: '日本歯科大学', address: '和歌山県西牟婁郡白浜町玉伝' )
Place.create(id: 19, name: '島根県立大学', address: '長崎県佐世保市新港町' )
Place.create(id: 20, name: '京王リース不二組合', address: '駿東郡小山町大胡田54丁目4644-5061' )
Place.create(id: 21, name: 'テンプ高島東洋有限会社', address: '岩瀬郡天栄村飯豊60丁目5435-6963' )
Place.create(id: 22, name: '有限会社ゴム工業グループピー', address: '芳賀郡芳賀町上延生48丁目6804-6555' )
Place.create(id: 23, name: '千代田エム北海道株式会社', address: '岡山市東区金岡西町27丁目9792-4892' )
Place.create(id: 24, name: '立命館アジア太平洋大学', address: '岩手県奥州市水沢区雀田' )
Place.create(id: 25, name: '札幌市立大学', address: '山形県鶴岡市岡山' )
Place.create(id: 26, name: 'ユアサエムアイカーボン合資会社', address: '高山市朝日町見座99丁目5331-2106' )
Place.create(id: 27, name: '帝京平成大学', address: '京都府舞鶴市吉田' )
Place.create(id: 28, name: '株式会社ストアバイエルクリエイト', address: '名古屋市中村区沖田町78丁目4478-8200' )
Place.create(id: 29, name: '松本大学', address: '鳥取県倉吉市見日町' )
Place.create(id: 30, name: 'フジゴルフプラス株式会社', address: '上北郡七戸町中村53丁目8378-2885' )

if Rails.env.development?
  Place.connection.execute("update sqlite_sequence set seq=30 where name='places'")
else
  Place.connection.execute("SELECT SETVAL('places_id_seq', 30, TRUE)")
end

# Status(状況)テーブルに初期値を投入(全件削除して再投入)
Status.delete_all
Status.create(id: 1, name: '担当未割当')
Status.create(id: 2, name: '実施待ち')
Status.create(id: 3, name: '実施中')
Status.create(id: 4, name: '完了')
if Rails.env.development?
  Status.connection.execute("update sqlite_sequence set seq=4 where name='statuses'")
else
  Status.connection.execute("SELECT SETVAL('statuses_id_seq', 4, TRUE)")
end

# Result(結果)テーブルに初期値を投入(全件削除して再投入)
Result.delete_all
Result.create(id: 1, name: '合格')
Result.create(id: 2, name: '不合格')
Result.create(id: 3, name: '状態不明')
Result.create(id: 4, name: '検査前')
if Rails.env.development?
  Result.connection.execute("update sqlite_sequence set seq=4 where name='results'")
else
  Result.connection.execute("SELECT SETVAL('results_id_seq', 4, TRUE)")
end

# Weather(天気)テーブルに初期値を投入(全件削除して再投入)
Weather.delete_all
Weather.create(id: 1, name: '晴')
Weather.create(id: 2, name: '曇')
Weather.create(id: 3, name: '雨')
Weather.create(id: 4, name: '雪')
if Rails.env.development?
  Weather.connection.execute("update sqlite_sequence set seq=4 where name='weathers'")
else
  Weather.connection.execute("SELECT SETVAL('weathers_id_seq', 4, TRUE)")
end

# Checkresult(チェック結果)テーブルに初期値を投入(全件削除して再投入)
Checkresult.delete_all
Checkresult.create(id: 1, name: '優')
Checkresult.create(id: 2, name: '良')
Checkresult.create(id: 3, name: '可')
Checkresult.create(id: 4, name: '不可')
if Rails.env.development?
  Checkresult.connection.execute("update sqlite_sequence set seq=4 where name='checkresults'")
else
  Checkresult.connection.execute("SELECT SETVAL('checkresults_id_seq', 4, TRUE)")
end

# Flag(フラグ)テーブルに初期値を投入(全件削除して再投入)
Flag.delete_all
Flag.create(id: 1, name: 'Open')
Flag.create(id: 2, name: 'Close')
if Rails.env.development?
  Weather.connection.execute("update sqlite_sequence set seq=2 where name='flasg'")
else
  Weather.connection.execute("SELECT SETVAL('flags_id_seq', 2, TRUE)")
end

##########################
### テスト用にデータを入れる（超暫定)
##########################

# Worker(作業者)テーブルにテスト用初期値を投入（全件削除して再投入）
Worker.delete_all
if Rails.env.development?
  Worker.connection.execute("delete from sqlite_sequence where name='workers'")
else
  Worker.connection.execute("SELECT SETVAL('workers_id_seq',1,FALSE)")
end
Worker.create( name: '谷川光正', division_id: 3 )
Worker.create( name: '村山音々', division_id: 4 )
Worker.create( name: '佐伯林檎', division_id: 5 )
Worker.create( name: '大竹美貴', division_id: 1 )
Worker.create( name: '平良朱里', division_id: 2 )
Worker.create( name: '渥美健吉', division_id: 3 )
Worker.create( name: '新倉満', division_id: 4 )
Worker.create( name: '松本真理子', division_id: 5 )
Worker.create( name: '湯川恒敏', division_id: 1 )
Worker.create( name: '田辺澄子', division_id: 2 )
Worker.create( name: '新垣香里', division_id: 3 )
Worker.create( name: '辻本恵美', division_id: 4 )
Worker.create( name: '高津一花', division_id: 5 )
Worker.create( name: '名取和弥', division_id: 1 )
Worker.create( name: '毛利豊子', division_id: 2 )
Worker.create( name: '矢野茉奈', division_id: 3 )
Worker.create( name: '高村一葉', division_id: 4 )
Worker.create( name: '角千代乃', division_id: 5 )
Worker.create( name: '滋賀浩二', division_id: 1 )
Worker.create( name: '三原清一郎', division_id: 2 )
Worker.create( name: '手島与三郎', division_id: 3 )
Worker.create( name: '小山柚衣', division_id: 4 )
Worker.create( name: '井田華蓮', division_id: 5 )
Worker.create( name: '正木唯', division_id: 1 )
Worker.create( name: '三井幸太郎', division_id: 2 )
Worker.create( name: '坂上宗雄', division_id: 3 )
Worker.create( name: '佐竹良雄', division_id: 4 )
Worker.create( name: '越智沙彩', division_id: 5 )
Worker.create( name: '佐竹恵利', division_id: 1 )
Worker.create( name: '宮下和之', division_id: 2 )
Worker.create( name: '長友碧依', division_id: 3 )
Worker.create( name: '藤村英俊', division_id: 4 )
Worker.create( name: '坪井晴雄', division_id: 5 )
Worker.create( name: '藤木咲子', division_id: 1 )
Worker.create( name: '米倉武男', division_id: 2 )
Worker.create( name: '柴田亜由美', division_id: 3 )
Worker.create( name: '坂野邦夫', division_id: 4 )
Worker.create( name: '仲村留吉', division_id: 5 )
Worker.create( name: '森田理', division_id: 1 )
Worker.create( name: '児玉莉子', division_id: 2 )
Worker.create( name: '関本花帆', division_id: 3 )
Worker.create( name: '岩永良子', division_id: 4 )
Worker.create( name: '高坂真理子', division_id: 5 )
Worker.create( name: '野村啓二', division_id: 1 )
Worker.create( name: '平松幸治', division_id: 2 )
Worker.create( name: '北田敏幸', division_id: 3 )
Worker.create( name: '山岸義美', division_id: 4 )
Worker.create( name: '坂上治', division_id: 5 )
Worker.create( name: '志賀棟上', division_id: 1 )
Worker.create( name: '塩谷信行', division_id: 2 )
Worker.create( name: '松沢信長', division_id: 3 )
Worker.create( name: '五味真樹', division_id: 4 )
Worker.create( name: '山岸良彦', division_id: 5 )
Worker.create( name: '荒井柚衣', division_id: 1 )
Worker.create( name: '中尾理子', division_id: 2 )
Worker.create( name: '森井双葉', division_id: 3 )
Worker.create( name: '清野久子', division_id: 4 )
Worker.create( name: '岩永翔子', division_id: 5 )
Worker.create( name: '田口昌己', division_id: 1 )
Worker.create( name: '戸田優奈', division_id: 2 )
Worker.create( name: '首藤瑞穂', division_id: 3 )
Worker.create( name: '富田隆吾', division_id: 4 )
Worker.create( name: '川嶋悠', division_id: 5 )
Worker.create( name: '金谷亮太', division_id: 1 )
Worker.create( name: '藤崎文音', division_id: 2 )
Worker.create( name: '浜野幸二', division_id: 3 )
Worker.create( name: '中島政次', division_id: 4 )
Worker.create( name: '渋谷洋二', division_id: 5 )
Worker.create( name: '増田綾花', division_id: 1 )
Worker.create( name: '安部和雄', division_id: 2 )
Worker.create( name: '武田利雄', division_id: 3 )
Worker.create( name: '花岡淑子', division_id: 4 )
Worker.create( name: '吉沢秀吉', division_id: 5 )
Worker.create( name: '足立五月', division_id: 1 )
Worker.create( name: '我妻忠男', division_id: 2 )
Worker.create( name: '鳥居顕子', division_id: 3 )
Worker.create( name: '高柳健吉', division_id: 4 )
Worker.create( name: '矢口孝宏', division_id: 5 )
Worker.create( name: '手島弘', division_id: 1 )
Worker.create( name: '渋谷美名子', division_id: 2 )
Worker.create( name: '日下部雅博', division_id: 3 )
Worker.create( name: '大山清次', division_id: 4 )
Worker.create( name: '宮島久男', division_id: 5 )
Worker.create( name: '田代紀子', division_id: 1 )
Worker.create( name: '中嶋優子', division_id: 2 )
Worker.create( name: '寺尾正敏', division_id: 3 )
Worker.create( name: '本橋紀之', division_id: 4 )
Worker.create( name: '長井利治', division_id: 5 )
Worker.create( name: '菅沼陽華', division_id: 1 )
Worker.create( name: '小山田聡子', division_id: 2 )
Worker.create( name: '長嶋歩', division_id: 3 )
Worker.create( name: '川口勇', division_id: 4 )
Worker.create( name: '菅野沙也佳', division_id: 5 )
Worker.create( name: '富山英世', division_id: 1 )
Worker.create( name: '広田浩司', division_id: 2 )
Worker.create( name: '安井敦', division_id: 3 )
Worker.create( name: '安部利恵', division_id: 4 )
Worker.create( name: '本村結芽', division_id: 5 )
Worker.create( name: '飛田繁雄', division_id: 1 )
Worker.create( name: '安斎優華', division_id: 2 )

# Equipment(設備)テーブルにテスト用初期値を投入（全件削除して再投入）
Equipment.delete_all
if Rails.env.development?
  Equipment.connection.execute("delete from sqlite_sequence where name='equipment'")
else
  Equipment.connection.execute("SELECT SETVAL('equipment_id_seq',1,FALSE)")
end
Equipment.create( name: '冷蔵庫', type_id: 2, place_id: 2, division_id: 3 )
Equipment.create( name: '洗濯機', type_id: 3, place_id: 3, division_id: 4 )
Equipment.create( name: '発電機', type_id: 1, place_id: 4, division_id: 5 )
Equipment.create( name: '懐中電灯', type_id: 2, place_id: 5, division_id: 2 )
Equipment.create( name: 'ラジオ', type_id: 3, place_id: 6, division_id: 3 )
Equipment.create( name: '大型テレビ', type_id: 1, place_id: 7, division_id: 4 )
Equipment.create( name: '発電施設', type_id: 2, place_id: 8, division_id: 5 )
Equipment.create( name: 'ポータブルテレビ', type_id: 3, place_id: 9, division_id: 2 )
Equipment.create( name: 'バッテリー', type_id: 1, place_id: 10, division_id: 3 )
Equipment.create( name: '拡声器', type_id: 2, place_id: 11, division_id: 4 )
Equipment.create( name: '冷蔵庫', type_id: 3, place_id: 12, division_id: 5 )
Equipment.create( name: '洗濯機', type_id: 1, place_id: 13, division_id: 2 )
Equipment.create( name: '発電機', type_id: 2, place_id: 14, division_id: 3 )
Equipment.create( name: '懐中電灯', type_id: 3, place_id: 15, division_id: 4 )
Equipment.create( name: 'ラジオ', type_id: 1, place_id: 16, division_id: 5 )
Equipment.create( name: '大型テレビ', type_id: 2, place_id: 17, division_id: 2 )
Equipment.create( name: '発電施設', type_id: 3, place_id: 18, division_id: 3 )
Equipment.create( name: 'ポータブルテレビ', type_id: 1, place_id: 19, division_id: 4 )
Equipment.create( name: 'バッテリー', type_id: 2, place_id: 20, division_id: 5 )
Equipment.create( name: '拡声器', type_id: 3, place_id: 21, division_id: 2 )
Equipment.create( name: '冷蔵庫', type_id: 1, place_id: 22, division_id: 3 )
Equipment.create( name: '洗濯機', type_id: 2, place_id: 23, division_id: 4 )
Equipment.create( name: '発電機', type_id: 3, place_id: 24, division_id: 5 )
Equipment.create( name: '懐中電灯', type_id: 1, place_id: 25, division_id: 2 )
Equipment.create( name: 'ラジオ', type_id: 2, place_id: 26, division_id: 3 )
Equipment.create( name: '大型テレビ', type_id: 3, place_id: 27, division_id: 4 )
Equipment.create( name: '発電施設', type_id: 1, place_id: 28, division_id: 5 )
Equipment.create( name: 'ポータブルテレビ', type_id: 2, place_id: 29, division_id: 2 )
Equipment.create( name: 'バッテリー', type_id: 3, place_id: 30, division_id: 3 )
Equipment.create( name: '拡声器', type_id: 1, place_id: 1, division_id: 4 )
Equipment.create( name: '冷蔵庫', type_id: 2, place_id: 2, division_id: 5 )
Equipment.create( name: '洗濯機', type_id: 3, place_id: 3, division_id: 2 )
Equipment.create( name: '発電機', type_id: 1, place_id: 4, division_id: 3 )
Equipment.create( name: '懐中電灯', type_id: 2, place_id: 5, division_id: 4 )
Equipment.create( name: 'ラジオ', type_id: 3, place_id: 6, division_id: 5 )
Equipment.create( name: '大型テレビ', type_id: 1, place_id: 7, division_id: 2 )
Equipment.create( name: '発電施設', type_id: 2, place_id: 8, division_id: 3 )
Equipment.create( name: 'ポータブルテレビ', type_id: 3, place_id: 9, division_id: 4 )
Equipment.create( name: 'バッテリー', type_id: 1, place_id: 10, division_id: 5 )
Equipment.create( name: '拡声器', type_id: 2, place_id: 11, division_id: 2 )
Equipment.create( name: '冷蔵庫', type_id: 3, place_id: 12, division_id: 3 )
Equipment.create( name: '洗濯機', type_id: 1, place_id: 13, division_id: 4 )
Equipment.create( name: '発電機', type_id: 2, place_id: 14, division_id: 5 )
Equipment.create( name: '懐中電灯', type_id: 3, place_id: 15, division_id: 2 )
Equipment.create( name: 'ラジオ', type_id: 1, place_id: 16, division_id: 3 )
Equipment.create( name: '大型テレビ', type_id: 2, place_id: 17, division_id: 4 )
Equipment.create( name: '発電施設', type_id: 3, place_id: 18, division_id: 5 )
Equipment.create( name: 'ポータブルテレビ', type_id: 1, place_id: 19, division_id: 2 )
Equipment.create( name: 'バッテリー', type_id: 2, place_id: 20, division_id: 3 )
Equipment.create( name: '拡声器', type_id: 3, place_id: 21, division_id: 4 )

# Inspection(点検)テーブルにテスト用初期値を投入（全件削除して再投入）
Inspection.delete_all
if Rails.env.development?
  Inspection.connection.execute("delete from sqlite_sequence where name='inspections'")
else
  Inspection.connection.execute("SELECT SETVAL('inspections_id_seq',1,FALSE)")
end
Inspection.create(targetyearmonth: '201502', equipment_id: 2, status_id: 2, worker_id: 4, result_id: 4, processingdate: '2015-03-01' )
Inspection.create(targetyearmonth: '201503', equipment_id: 3, status_id: 2, worker_id: 5, result_id: 4, processingdate: '2015-03-01' )
Inspection.create(targetyearmonth: '201504', equipment_id: 4, status_id: 2, worker_id: 6, result_id: 4, processingdate: '2015-03-01' )
Inspection.create(targetyearmonth: '201505', equipment_id: 5, status_id: 2, worker_id: 7, result_id: 4, processingdate: '2015-03-01' )
Inspection.create(targetyearmonth: '201506', equipment_id: 6, status_id: 2, worker_id: 8, result_id: 4, processingdate: '2015-03-01' )
Inspection.create(targetyearmonth: '201507', equipment_id: 7, status_id: 2, worker_id: 3, result_id: 4, processingdate: '2015-03-01' )
Inspection.create(targetyearmonth: '201508', equipment_id: 8, status_id: 2, worker_id: 4, result_id: 4, processingdate: '2015-03-01' )
Inspection.create(targetyearmonth: '201509', equipment_id: 9, status_id: 2, worker_id: 5, result_id: 4, processingdate: '2015-03-01' )
Inspection.create(targetyearmonth: '201510', equipment_id: 10, status_id: 2, worker_id: 6, result_id: 4, processingdate: '2015-03-01' )
Inspection.create(targetyearmonth: '201401', equipment_id: 11, status_id: 2, worker_id: 7, result_id: 4, processingdate: '2015-03-01' )
Inspection.create(targetyearmonth: '201402', equipment_id: 12, status_id: 2, worker_id: 8, result_id: 4, processingdate: '2015-03-01' )
Inspection.create(targetyearmonth: '201403', equipment_id: 13, status_id: 2, worker_id: 3, result_id: 4, processingdate: '2015-03-01' )
Inspection.create(targetyearmonth: '201502', equipment_id: 14, status_id: 2, worker_id: 4, result_id: 4, processingdate: '2015-03-01' )
Inspection.create(targetyearmonth: '201503', equipment_id: 15, status_id: 2, worker_id: 5, result_id: 4, processingdate: '2015-03-01' )
Inspection.create(targetyearmonth: '201504', equipment_id: 16, status_id: 2, worker_id: 6, result_id: 4, processingdate: '2015-03-01' )
Inspection.create(targetyearmonth: '201505', equipment_id: 17, status_id: 2, worker_id: 7, result_id: 4, processingdate: '2015-03-01' )
Inspection.create(targetyearmonth: '201506', equipment_id: 18, status_id: 2, worker_id: 8, result_id: 4, processingdate: '2015-03-01' )
Inspection.create(targetyearmonth: '201507', equipment_id: 19, status_id: 2, worker_id: 3, result_id: 4, processingdate: '2015-03-01' )
Inspection.create(targetyearmonth: '201508', equipment_id: 20, status_id: 2, worker_id: 4, result_id: 4, processingdate: '2015-03-01' )
Inspection.create(targetyearmonth: '201509', equipment_id: 1, status_id: 2, worker_id: 5, result_id: 4, processingdate: '2015-03-01' )
Inspection.create(targetyearmonth: '201510', equipment_id: 2, status_id: 2, worker_id: 6, result_id: 4, processingdate: '2015-03-01' )
Inspection.create(targetyearmonth: '201401', equipment_id: 3, status_id: 2, worker_id: 7, result_id: 4, processingdate: '2015-03-01' )
Inspection.create(targetyearmonth: '201402', equipment_id: 4, status_id: 2, worker_id: 8, result_id: 4, processingdate: '2015-03-01' )
Inspection.create(targetyearmonth: '201403', equipment_id: 5, status_id: 2, worker_id: 3, result_id: 4, processingdate: '2015-03-01' )
Inspection.create(targetyearmonth: '201502', equipment_id: 6, status_id: 2, worker_id: 4, result_id: 4, processingdate: '2015-03-01' )
Inspection.create(targetyearmonth: '201503', equipment_id: 7, status_id: 2, worker_id: 5, result_id: 4, processingdate: '2015-03-01' )
Inspection.create(targetyearmonth: '201504', equipment_id: 8, status_id: 2, worker_id: 6, result_id: 4, processingdate: '2015-03-01' )
Inspection.create(targetyearmonth: '201505', equipment_id: 9, status_id: 2, worker_id: 7, result_id: 4, processingdate: '2015-03-01' )
Inspection.create(targetyearmonth: '201506', equipment_id: 10, status_id: 2, worker_id: 8, result_id: 4, processingdate: '2015-03-01' )
Inspection.create(targetyearmonth: '201507', equipment_id: 11, status_id: 2, worker_id: 3, result_id: 4, processingdate: '2015-03-01' )
Inspection.create(targetyearmonth: '201508', equipment_id: 12, status_id: 2, worker_id: 4, result_id: 4, processingdate: '2015-03-01' )
Inspection.create(targetyearmonth: '201509', equipment_id: 13, status_id: 2, worker_id: 5, result_id: 4, processingdate: '2015-03-01' )
Inspection.create(targetyearmonth: '201510', equipment_id: 14, status_id: 2, worker_id: 6, result_id: 4, processingdate: '2015-03-01' )
Inspection.create(targetyearmonth: '201401', equipment_id: 15, status_id: 2, worker_id: 7, result_id: 4, processingdate: '2015-03-01' )
Inspection.create(targetyearmonth: '201402', equipment_id: 16, status_id: 2, worker_id: 8, result_id: 4, processingdate: '2015-03-01' )
Inspection.create(targetyearmonth: '201403', equipment_id: 17, status_id: 2, worker_id: 3, result_id: 4, processingdate: '2015-03-01' )
Inspection.create(targetyearmonth: '201502', equipment_id: 18, status_id: 2, worker_id: 4, result_id: 4, processingdate: '2015-03-01' )
Inspection.create(targetyearmonth: '201503', equipment_id: 19, status_id: 2, worker_id: 5, result_id: 4, processingdate: '2015-03-01' )
Inspection.create(targetyearmonth: '201504', equipment_id: 20, status_id: 2, worker_id: 6, result_id: 4, processingdate: '2015-03-01' )
Inspection.create(targetyearmonth: '201505', equipment_id: 1, status_id: 2, worker_id: 7, result_id: 4, processingdate: '2015-03-01' )
Inspection.create(targetyearmonth: '201506', equipment_id: 2, status_id: 2, worker_id: 8, result_id: 4, processingdate: '2015-03-01' )
Inspection.create(targetyearmonth: '201507', equipment_id: 3, status_id: 2, worker_id: 3, result_id: 4, processingdate: '2015-03-01' )
Inspection.create(targetyearmonth: '201508', equipment_id: 4, status_id: 2, worker_id: 4, result_id: 4, processingdate: '2015-03-01' )
Inspection.create(targetyearmonth: '201509', equipment_id: 5, status_id: 2, worker_id: 5, result_id: 4, processingdate: '2015-03-01' )
Inspection.create(targetyearmonth: '201510', equipment_id: 6, status_id: 2, worker_id: 6, result_id: 4, processingdate: '2015-03-01' )
Inspection.create(targetyearmonth: '201401', equipment_id: 7, status_id: 2, worker_id: 7, result_id: 4, processingdate: '2015-03-01' )
Inspection.create(targetyearmonth: '201402', equipment_id: 8, status_id: 2, worker_id: 8, result_id: 4, processingdate: '2015-03-01' )
Inspection.create(targetyearmonth: '201403', equipment_id: 9, status_id: 2, worker_id: 3, result_id: 4, processingdate: '2015-03-01' )
Inspection.create(targetyearmonth: '201502', equipment_id: 10, status_id: 2, worker_id: 4, result_id: 4, processingdate: '2015-03-01' )
Inspection.create(targetyearmonth: '201503', equipment_id: 11, status_id: 2, worker_id: 5, result_id: 4, processingdate: '2015-03-01' )
Inspection.create(targetyearmonth: '201504', equipment_id: 12, status_id: 2, worker_id: 6, result_id: 4, processingdate: '2015-03-01' )
Inspection.create(targetyearmonth: '201505', equipment_id: 13, status_id: 2, worker_id: 7, result_id: 4, processingdate: '2015-03-01' )
Inspection.create(targetyearmonth: '201506', equipment_id: 14, status_id: 2, worker_id: 8, result_id: 4, processingdate: '2015-03-01' )
Inspection.create(targetyearmonth: '201507', equipment_id: 15, status_id: 2, worker_id: 3, result_id: 4, processingdate: '2015-03-01' )
Inspection.create(targetyearmonth: '201508', equipment_id: 16, status_id: 2, worker_id: 4, result_id: 4, processingdate: '2015-03-01' )
Inspection.create(targetyearmonth: '201509', equipment_id: 17, status_id: 2, worker_id: 5, result_id: 4, processingdate: '2015-03-01' )
Inspection.create(targetyearmonth: '201510', equipment_id: 18, status_id: 2, worker_id: 6, result_id: 4, processingdate: '2015-03-01' )
Inspection.create(targetyearmonth: '201401', equipment_id: 19, status_id: 2, worker_id: 7, result_id: 4, processingdate: '2015-03-01' )
Inspection.create(targetyearmonth: '201402', equipment_id: 20, status_id: 2, worker_id: 8, result_id: 4, processingdate: '2015-03-01' )
Inspection.create(targetyearmonth: '201403', equipment_id: 1, status_id: 2, worker_id: 3, result_id: 4, processingdate: '2015-03-01' )
Inspection.create(targetyearmonth: '201502', equipment_id: 2, status_id: 2, worker_id: 4, result_id: 4, processingdate: '2015-03-01' )
Inspection.create(targetyearmonth: '201503', equipment_id: 3, status_id: 2, worker_id: 5, result_id: 4, processingdate: '2015-03-01' )
Inspection.create(targetyearmonth: '201504', equipment_id: 4, status_id: 2, worker_id: 6, result_id: 4, processingdate: '2015-03-01' )
Inspection.create(targetyearmonth: '201505', equipment_id: 5, status_id: 2, worker_id: 7, result_id: 4, processingdate: '2015-03-01' )
Inspection.create(targetyearmonth: '201506', equipment_id: 6, status_id: 2, worker_id: 8, result_id: 4, processingdate: '2015-03-01' )
Inspection.create(targetyearmonth: '201507', equipment_id: 7, status_id: 2, worker_id: 3, result_id: 4, processingdate: '2015-03-01' )
Inspection.create(targetyearmonth: '201508', equipment_id: 8, status_id: 2, worker_id: 4, result_id: 4, processingdate: '2015-03-01' )
Inspection.create(targetyearmonth: '201509', equipment_id: 9, status_id: 2, worker_id: 5, result_id: 4, processingdate: '2015-03-01' )
Inspection.create(targetyearmonth: '201510', equipment_id: 10, status_id: 2, worker_id: 6, result_id: 4, processingdate: '2015-03-01' )
Inspection.create(targetyearmonth: '201401', equipment_id: 11, status_id: 2, worker_id: 7, result_id: 4, processingdate: '2015-03-01' )
Inspection.create(targetyearmonth: '201402', equipment_id: 12, status_id: 2, worker_id: 8, result_id: 4, processingdate: '2015-03-01' )
Inspection.create(targetyearmonth: '201403', equipment_id: 13, status_id: 2, worker_id: 3, result_id: 4, processingdate: '2015-03-01' )
Inspection.create(targetyearmonth: '201502', equipment_id: 14, status_id: 2, worker_id: 4, result_id: 4, processingdate: '2015-03-01' )
Inspection.create(targetyearmonth: '201503', equipment_id: 15, status_id: 2, worker_id: 5, result_id: 4, processingdate: '2015-03-01' )
Inspection.create(targetyearmonth: '201504', equipment_id: 16, status_id: 2, worker_id: 6, result_id: 4, processingdate: '2015-03-01' )
Inspection.create(targetyearmonth: '201505', equipment_id: 17, status_id: 2, worker_id: 7, result_id: 4, processingdate: '2015-03-01' )
Inspection.create(targetyearmonth: '201506', equipment_id: 18, status_id: 2, worker_id: 8, result_id: 4, processingdate: '2015-03-01' )
Inspection.create(targetyearmonth: '201507', equipment_id: 19, status_id: 2, worker_id: 3, result_id: 4, processingdate: '2015-03-01' )
Inspection.create(targetyearmonth: '201508', equipment_id: 20, status_id: 2, worker_id: 4, result_id: 4, processingdate: '2015-03-01' )
Inspection.create(targetyearmonth: '201509', equipment_id: 1, status_id: 2, worker_id: 5, result_id: 4, processingdate: '2015-03-01' )
Inspection.create(targetyearmonth: '201510', equipment_id: 2, status_id: 2, worker_id: 6, result_id: 4, processingdate: '2015-03-01' )
Inspection.create(targetyearmonth: '201401', equipment_id: 3, status_id: 2, worker_id: 7, result_id: 4, processingdate: '2015-03-01' )
Inspection.create(targetyearmonth: '201402', equipment_id: 4, status_id: 2, worker_id: 8, result_id: 4, processingdate: '2015-03-01' )
Inspection.create(targetyearmonth: '201403', equipment_id: 5, status_id: 2, worker_id: 3, result_id: 4, processingdate: '2015-03-01' )